### ISSUE TITLE
Error if otelExtension is not set in dependencies

### ISSUE THREAD

**Issue by jamesbassett** [ryandens/javaagent-gradle-plugin#176]
I've recently tried upgrading our custom otel distribution from 0.5.2. to 0.7.0 and encountered the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':opentelemetry-java-agent:extendedAgent'.
> Expected configuration ':opentelemetry-java-agent:otelExtension' to contain exactly one file, however, it contains no files.
```

The stacktrace:
```
Caused by: java.lang.IllegalStateException: Expected configuration ':opentelemetry-java-agent:otelExtension' to contain exactly one file, however, it contains no files.
        at org.gradle.api.internal.file.AbstractFileCollection.getSingleFile(AbstractFileCollection.java:153)
        at org.gradle.api.internal.artifacts.configurations.DefaultUnlockedConfiguration_Decorated.getSingleFile(Unknown Source)
        at com.ryandens.javaagent.otel.JavaagentOTelModificationPlugin$apply$extendedAgent$1$3.invoke(JavaagentOTelModificationPlugin.kt:57)
        at com.ryandens.javaagent.otel.JavaagentOTelModificationPlugin$apply$extendedAgent$1$3.invoke(JavaagentOTelModificationPlugin.kt:57)
        at com.ryandens.javaagent.otel.JavaagentOTelModificationPlugin$apply$extendedAgent$1.invoke$lambda$2(JavaagentOTelModificationPlugin.kt:57)
```

We don't use `otelExtension` in our dependencies but it seems like it is now required after [this change](https://github.com/ryandens/javaagent-gradle-plugin/pull/168/files#diff-83d36b3e766e470c71ef1420617937717828310005145493c4e8a7f7d94ad1aeR57)

If I add it in (based on the example in that PR) it works again.

```
dependencies {
    otel(projectLibs.opentelemetry.javaagent)
    // TODO it seems like otelExtension is now mandatory? i.e.
    // otelExtension("io.opentelemetry.contrib:opentelemetry-samplers:1.12.0-alpha")
    otelInstrumentation(project(":otel-extensions", "shadow"))
}
```

**Comment by ryandens** [comment]
Thanks for the report! Definitely not intentional, i'll fix when i get the chance

**Comment by jamesbassett** [comment]
Hi just wondering if you've had time to look at this yet?

**Comment by ryandens** [comment]
Nope!

**Comment by jamesbassett** [comment]
@ryandens I've just raised #209 to resolve this
