### ISSUE TITLE
Plugin is incompatible with Gradle 8.4 + Kotlin 1.6.21 since 0.4.1

### ISSUE THREAD

**Issue by felixscheinost** [ryandens/javaagent-gradle-plugin#49]
This plugin unfortunately seems to incompatible with our Spring Boot 2.7.x projects since 0.4.1 (maybe due to a Kotlin plugin update?).

We use Gradle 8.4 and Kotlin 1.6.21.

0.4.0 works while 0.4.1 and all newer releases fail with:

```
java.lang.NoSuchFieldError: KOTLIN_STAT_ENABLED_PROPERTY
        at org.jetbrains.kotlin.gradle.plugin.KotlinGradleBuildServices.<clinit>(KotlinGradleBuildServices.kt:52)
        at org.jetbrains.kotlin.gradle.plugin.KotlinBasePluginWrapper.apply(KotlinPluginWrapper.kt:92)
        at org.jetbrains.kotlin.gradle.plugin.KotlinBasePluginWrapper.apply(KotlinPluginWrapper.kt:54)
```

Upgrading from Kotlin 1.6.21 to 1.7.0 fixes the problem but that's unfortunate as 1.6.21 is the version that is officially supported by Spring Boot 2.7.x and 3.x is a major change that can't easily be done yet for some projects.

Is there anything that can be done?

Example project https://github.com/felixscheinost/reproduce-javaagent-gradle-plugin-issue

Thanks!

**Comment by ryandens** [comment]
Hi @felixscheinost, thanks for pointing this out and for providing the reproducer project! I don't have a formal backwards compatibility policy for this project yet, but I'll take a look at what makes sense in the context of this issue and work on clarifying this for the future. I should have a response to you later next week

**Comment by felixscheinost** [comment]
Yeah, I understand that with Kotlin it is a little bit difficult to keep backwards compatibility sometimes. It may also not be worth it, if it means restricting the library code too much. But maybe there is a solution and if not I maybe a test could be added which tests a baseline of compatible versions.

**Comment by ryandens** [comment]
👋 Hi @felixscheinost, I believe you can fix this issue in your build without limiting this project to older kotlin versions. Take a look at [this solution](https://github.com/felixscheinost/reproduce-javaagent-gradle-plugin-issue/pull/1) where the javaagent dependency is managed in an included build (buildSrc) and the subproject uses an old kotlin version but still applies the plugin.

**Comment by felixscheinost** [comment]
Thank you very much for coming up with that solution, even though I don't completely understand how that makes a difference 😄 Does the resolution of transitive dependencies work differentlly when included in `buildSrc` compared to when included in `plugins` block directly? 

I haven't had a chance yet to test this in the upstream project but I could reproduce that your solution fixes the problem in my example project.

This issue can probably be closed or do you think there's anything left to do?
